---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tell a story
description: Create a webpage to tell a story, joke, or poem
pdf: resources/rpfi-tell-a-story.pdf
original_url: https://codeclubprojects.org/en-GB/webdev/editor-tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
landing: true
steps:
  - title: Add the opening line
  - title: Add a second panel
    completion:
      - engaged
  - title: Finish your story
    completion:
      - internal
      - external
  - title: Challenge
    challenge: true
